language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t ghoshd1/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ghoshd1/docker-react npm run test